/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkLogRouteImport } from './routes/work-log'
import { Route as TodosRouteImport } from './routes/todos'
import { Route as StatsRouteImport } from './routes/stats'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PomodoroRouteImport } from './routes/pomodoro'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as HabitsRouteImport } from './routes/habits'
import { Route as IndexRouteImport } from './routes/index'

const WorkLogRoute = WorkLogRouteImport.update({
  id: '/work-log',
  path: '/work-log',
  getParentRoute: () => rootRouteImport,
} as any)
const TodosRoute = TodosRouteImport.update({
  id: '/todos',
  path: '/todos',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsRoute = StatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PomodoroRoute = PomodoroRouteImport.update({
  id: '/pomodoro',
  path: '/pomodoro',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const HabitsRoute = HabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/habits': typeof HabitsRoute
  '/notes': typeof NotesRoute
  '/pomodoro': typeof PomodoroRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/todos': typeof TodosRoute
  '/work-log': typeof WorkLogRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/habits': typeof HabitsRoute
  '/notes': typeof NotesRoute
  '/pomodoro': typeof PomodoroRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/todos': typeof TodosRoute
  '/work-log': typeof WorkLogRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/habits': typeof HabitsRoute
  '/notes': typeof NotesRoute
  '/pomodoro': typeof PomodoroRoute
  '/settings': typeof SettingsRoute
  '/stats': typeof StatsRoute
  '/todos': typeof TodosRoute
  '/work-log': typeof WorkLogRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/habits'
    | '/notes'
    | '/pomodoro'
    | '/settings'
    | '/stats'
    | '/todos'
    | '/work-log'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/habits'
    | '/notes'
    | '/pomodoro'
    | '/settings'
    | '/stats'
    | '/todos'
    | '/work-log'
  id:
    | '__root__'
    | '/'
    | '/habits'
    | '/notes'
    | '/pomodoro'
    | '/settings'
    | '/stats'
    | '/todos'
    | '/work-log'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HabitsRoute: typeof HabitsRoute
  NotesRoute: typeof NotesRoute
  PomodoroRoute: typeof PomodoroRoute
  SettingsRoute: typeof SettingsRoute
  StatsRoute: typeof StatsRoute
  TodosRoute: typeof TodosRoute
  WorkLogRoute: typeof WorkLogRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work-log': {
      id: '/work-log'
      path: '/work-log'
      fullPath: '/work-log'
      preLoaderRoute: typeof WorkLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/todos': {
      id: '/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof TodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats': {
      id: '/stats'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pomodoro': {
      id: '/pomodoro'
      path: '/pomodoro'
      fullPath: '/pomodoro'
      preLoaderRoute: typeof PomodoroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/habits': {
      id: '/habits'
      path: '/habits'
      fullPath: '/habits'
      preLoaderRoute: typeof HabitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HabitsRoute: HabitsRoute,
  NotesRoute: NotesRoute,
  PomodoroRoute: PomodoroRoute,
  SettingsRoute: SettingsRoute,
  StatsRoute: StatsRoute,
  TodosRoute: TodosRoute,
  WorkLogRoute: WorkLogRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
